### ISSUE TITLE
Push fresh app RoR with Ruby 2.2.3p173 and Rails 4.2.4

### ISSUE THREAD

**Issue by faisal-rommy** [rails-banten/disbudpar-gov#1]
Please @noormaulida make fresh RoR app and push to this repo

**Comment by noormaulida** [comment]
oke bos

On Wed, Oct 28, 2015 at 4:49 PM, faisal-rommy notifications@github.com
wrote:

> Assigned #1 https://github.com/rails-banten/disbudpar-gov/issues/1 to
> @noormaulida https://github.com/noormaulida.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-banten/disbudpar-gov/issues/1#event-447785181.

## 

Regards,
_Noor Maulida_
_Junior Software Engineer_

Jl. Pejaten Barat 2 No. 3A, Pejaten Barat
Pasar Minggu, Jakarta Selatan - 12510
T: (021) 719 6877  |  F: (021) 719 6877
M: 0857 14896 323
http://www.suitmedia.com/

**Comment by noormaulida** [comment]
done bro
