### ISSUE TITLE
Discussion database and enhancement tables

### ISSUE THREAD

**Issue by faisal-rommy** [rails-banten/disbudpar-gov#2]
@noormaulida and @mahendra-aditya, database apa yang akan kita gunakan? sy prefer postgre tp mysql jg no prob. database yg lama menggunakan mysql dan tidak terstruktur. saran saya atur ulang dr awal masalah db jd menggunakan db selain mysql pun tdk masalah

**Comment by faisal-rommy** [comment]
ping! halo gmn nih?

**Comment by noormaulida** [comment]
kalo aku prefer mysql. postgre jg gak masalah

On Wed, Oct 28, 2015 at 5:23 PM, faisal-rommy notifications@github.com
wrote:

> ping! halo gmn nih?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rails-banten/disbudpar-gov/issues/2#issuecomment-151792658
> .

## 

Regards,
_Noor Maulida_
_Junior Software Engineer_

Jl. Pejaten Barat 2 No. 3A, Pejaten Barat
Pasar Minggu, Jakarta Selatan - 12510
T: (021) 719 6877  |  F: (021) 719 6877
M: 0857 14896 323
http://www.suitmedia.com/

**Comment by mahendra-aditya** [comment]
MySQL, please

**Comment by faisal-rommy** [comment]
ok MySQL, draft db yg kemarin terlampir di email ya, thanks
